#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=03:00:00
#SBATCH --mem=10G
#SBATCH -J AnnotateProteins
#SBATCH -o AnnotateProteins.o%j

#=====================================================================
# This script runs: AnnotateProteins.R
# Submited on: Tue Oct 23 11:02:50 EDT 2018
#=====================================================================

# Work Directory
cd /mnt/research/NMDL/KER_Glycogen_and_RER_Thoroughbred/Proteomics/RER_Thoroughbred_Melissa_20180817/AnnotateProteins

# Run R Code
R -e 'library("knitr");knitr::spin ("AnnotateProteins.R")'

# Add metadata to md file
cat .metadata AnnotateProteins.md > tmp; mv tmp AnnotateProteins.md

# Render HTML
R -e 'library("prettydoc");rmarkdown::render ("AnnotateProteins.md")'

# Job Details
echo Job Details
scontrol show job $SLURM_JOB_ID
